### ISSUE TITLE
Incorrect chapter 8 logic

### ISSUE THREAD

**Issue by isaacd27** [Phantom5800/pmr-tracker#16]
the logic for the final chapter does not consider bombette or sushi or ultra boots to be required, even though they all are, it only considers the 7 star spirits and 5 keys to be required, even though you can skip using a key with a glitch

**Comment by Phantom5800** [comment]
The logic was originally written where you need all star spirits to get to chapter 8, so partner requirements were already assumed to have been met. Since that's no longer the case, I added the additional logic for requiring bombette, parakarry, bow and lakilester to get through the basement when not using faster bowser's castle. This won't generally come up now because more options need to be added to control star spirit requirements (#17).

Sushie and the Ultra Boots are never actually "required" because the flood room can be bypassed entirely with a key. You may need them for checks, but you will theoretically never need them to actually complete a seed. The key requirements are set to 5 because only glitchless logic is accounted for. #2 is for covering glitch logic when the community has made decisions on what glitches should be allowed for races, etc.
