### ISSUE TITLE
"Chapter beatable" logic for chapters 1 and 7 seems off

### ISSUE THREAD

**Issue by icebound777** [Phantom5800/pmr-tracker#9]
Chapter 1 should be beatable on
* **4 Fortress Keys**, and
* **Kooper**

but the tracker seems to also require Bombette?

Chapter 7 should be beatable on
* **Warehouse Key**, and
* **Bucket**, and
* **Scarf**, and
* **Star Stone**, and
* **Red Key**, and
* **Palace Key**, and
* **Super Boots**, and
* **Kooper**, and
* **Bombette**, and
* **Sushie** or **Blue House Open**

but the tracker seems to disregard that last line (entering chapter 7). Unless the tracker only considers the chapter itself, and not how you get there.

**Comment by Phantom5800** [comment]
You're correct on chapter 1. A lot of these conditions were just based on my speedrun experience, but while bombette does open a lot, she is not technically required. For chapter 7 I will add Sushie or Blue House Open as a condition because if we disregard getting to the chapter I feel there are other edge cases that would come up.

Another questionable one is chapter 5, since the tracker does not currently think bombette is required. I know we've discussed the softlock being potentially fixed in a variety of ways, so I'm hesitant to make a call on that for the tracker itself, but another ticket may need to be made for that depending on the final decision on how it is handled.

**Comment by Phantom5800** [comment]
I guess to add on, will odd key opening the door from outside remain? I recall it was originally not supposed to be in the seeds, but I quite a few people have likely expressed that they like the change.

**Comment by icebound777** [comment]
> I guess to add on, will odd key opening the door from outside remain?

Unclear at the moment. I could see an addition to the "Blue House Open" option, where instead of "open" and "not open" you could choose "not open, but openable from outside", with a visible lock placed there. However this has not yet been discussed

**Comment by Phantom5800** [comment]
Awesome, since this issue has been handled as originally written I'll close it, but please keep making more issues as things change or you find stuff!
