### ISSUE TITLE
Wrong number of magical seeds imported in settings

### ISSUE THREAD

**Issue by WyWayt** [Phantom5800/pmr-tracker#95]
I imported my Seed ID and had the seeds you need to access Flower Field set to Random, somehow the settings in the tracker were set to 5 seeds needed, which shouldn't even be possible.

**Comment by christianlegge** [comment]
Just added the fix to #94. This is happening because the seed settings API doesn't know how many seeds you need on Random, and the Random setting is encoded with the number 5. So unfortunately there's no way to automatically sync the tracker to the amount of seeds you actually need, you'd have to go to Toad Town ingame and then edit the seed settings yourself if you want that. But the number showing up as 5 is unintended, so that part is fixed. It'll just default to 4.
